unparse_python, fix recursive calls, fix allow_delayed_objects
Otherwise, you might run into:

AssertionError: DelayedBase object can not be passed if `allow_delayed_objects` is not set, as this will cause breaking hashes.